### ISSUE TITLE
Release does not work as expected

### ISSUE THREAD

**Issue by jecoz** [booster-pocket-router/www#3]
It looks like we remove too many files in the `gh-pages` branch when releasing -- we have to restart github pages setting to see the release changes.

**Comment by philipgiuliani** [comment]
This is probably because we are deleting the CNAME file and re-creating it. We should just keep it.

**Comment by jecoz** [comment]
Apparently we already [avoid that](https://github.com/booster-pocket-router/www/blob/bba32f63a224748ee9f3d60628fa242f9d8c1d24/.github/workflows/release.yml#L36)!

**Comment by philipgiuliani** [comment]
I think I cannot trigger a delpoyment. Can you try?

**Comment by jecoz** [comment]
Hey @philipgiuliani, I added you as maintainer now and I triggered a deployment. It does not work though. I'm checking it out too now.

**Comment by jecoz** [comment]
@philipgiuliani now we cannot publish a new version unless a change is performed 😂

**Comment by philipgiuliani** [comment]
Releases seem to work as expected now!
Just deployed a new version and it went online successfully!
